
//Set path to SmartSlog KP Library
#include <smartslog/generic.h>

#ifndef _GENERATED_ONTOLOGY
#define	_GENERATED_ONTOLOGY


#ifdef	__cplusplus
extern "C" {
#endif


#define INCLUDE_ALL_ONT_ENTITIES 1
#ifdef INCLUDE_ALL_ONT_ENTITIES

#define INCLUDE_PROPERTY_ISEVENTINCLUDEDIN 1
#define INCLUDE_PROPERTY_ISTASKOF 1
#define INCLUDE_PROPERTY_INCLUDESTIME 1
#define INCLUDE_PROPERTY_HASOPERATINGPROPERTY 1
#define INCLUDE_PROPERTY_HASPOSTCONDITION 1
#define INCLUDE_PROPERTY_ISREALIZEDBY 1
#define INCLUDE_PROPERTY_HASMEASUREMENTCAPABILITY 1
#define INCLUDE_PROPERTY_ISCHARACTERIZEDBY 1
#define INCLUDE_PROPERTY_REALIZES 1
#define INCLUDE_PROPERTY_OBJECT 1
#define INCLUDE_PROPERTY_HASINPUT 1
#define INCLUDE_PROPERTY_HASPRECONDITION 1
#define INCLUDE_PROPERTY_INCLUDESEVENT 1
#define INCLUDE_PROPERTY_FORPROPERTY 1
#define INCLUDE_PROPERTY_ISPARTOF 1
#define INCLUDE_PROPERTY_CONCEPTUALIZES 1
#define INCLUDE_PROPERTY_OBSERVES 1
#define INCLUDE_PROPERTY_ISOBSERVABLEAT 1
#define INCLUDE_PROPERTY_IMPLEMENTS 1
#define INCLUDE_PROPERTY_INVOLVESAGENT 1
#define INCLUDE_PROPERTY_ISCOVEREDBY 1
#define INCLUDE_PROPERTY_UNIFIES 1
#define INCLUDE_PROPERTY_DEPLOYMENTPROCESSPART 1
#define INCLUDE_PROPERTY_PREDICATE 1
#define INCLUDE_PROPERTY_CONCRETELYEXPRESSES 1
#define INCLUDE_PROPERTY_OVERLAPS 1
#define INCLUDE_PROPERTY_HASCOMPONENT 1
#define INCLUDE_PROPERTY_ISPROPERTYOF 1
#define INCLUDE_PROPERTY_ISSUPERORDINATEDTO 1
#define INCLUDE_PROPERTY_ISROLEOF 1
#define INCLUDE_PROPERTY_INCLUDESAGENT 1
#define INCLUDE_PROPERTY_ISPOSTCONDITIONOF 1
#define INCLUDE_PROPERTY_OBSERVATIONSAMPLINGTIME 1
#define INCLUDE_PROPERTY_HASOPERATINGRANGE 1
#define INCLUDE_PROPERTY_DIRECTLYFOLLOWS 1
#define INCLUDE_PROPERTY_HASSURVIVALPROPERTY 1
#define INCLUDE_PROPERTY_PRECEDES 1
#define INCLUDE_PROPERTY_HASMEASUREMENTPROPERTY 1
#define INCLUDE_PROPERTY_STARTTIME 1
#define INCLUDE_PROPERTY_EXPANDS 1
#define INCLUDE_PROPERTY_HASSETTING 1
#define INCLUDE_PROPERTY_ISREFERENCEOFINFORMATIONREALIZEDBY 1
#define INCLUDE_PROPERTY_HASSUBSYSTEM 1
#define INCLUDE_PROPERTY_ISEXPANDEDIN 1
#define INCLUDE_PROPERTY_ISRELATEDTODESCRIPTION 1
#define INCLUDE_PROPERTY_ISCONSTRAINTFOR 1
#define INCLUDE_PROPERTY_HASREGION 1
#define INCLUDE_PROPERTY_NEARTO 1
#define INCLUDE_PROPERTY_HASPROPERTY 1
#define INCLUDE_PROPERTY_FARFROM 1
#define INCLUDE_PROPERTY_FOLLOWS 1
#define INCLUDE_PROPERTY_ISDESCRIBEDBY 1
#define INCLUDE_PROPERTY_ISPROXYFOR 1
#define INCLUDE_PROPERTY_ISTIMEINCLUDEDIN 1
#define INCLUDE_PROPERTY_SPECIALIZES 1
#define INCLUDE_PROPERTY_ACTSTHROUGH 1
#define INCLUDE_PROPERTY_INCONDITION 1
#define INCLUDE_PROPERTY_HASDEPLOYMENT 1
#define INCLUDE_PROPERTY_INCLUDESACTION 1
#define INCLUDE_PROPERTY_FIRST 1
#define INCLUDE_PROPERTY_HASPARAMETER 1
#define INCLUDE_PROPERTY_HASMEMBER 1
#define INCLUDE_PROPERTY_HASCONSTITUENT 1
#define INCLUDE_PROPERTY_FEATUREOFINTEREST 1
#define INCLUDE_PROPERTY_ENDTIME 1
#define INCLUDE_PROPERTY_ISAGENTINCLUDEDIN 1
#define INCLUDE_PROPERTY_OBSERVEDPROPERTY 1
#define INCLUDE_PROPERTY_ISCLASSIFIEDBY 1
#define INCLUDE_PROPERTY_COVERS 1
#define INCLUDE_PROPERTY_ONPLATFORM 1
#define INCLUDE_PROPERTY_HASPROXY 1
#define INCLUDE_PROPERTY_HASINTERVALDATE 1
#define INCLUDE_PROPERTY_SENSINGMETHODUSED 1
#define INCLUDE_PROPERTY_HASPARTICIPANT 1
#define INCLUDE_PROPERTY_ISQUALITYOF 1
#define INCLUDE_PROPERTY_ISABOUT 1
#define INCLUDE_PROPERTY_USESCONCEPT 1
#define INCLUDE_PROPERTY_HASOUTPUT 1
#define INCLUDE_PROPERTY_ISSPECIALIZEDBY 1
#define INCLUDE_PROPERTY_DEFINES 1
#define INCLUDE_PROPERTY_REALIZESINFORMATIONABOUT 1
#define INCLUDE_PROPERTY_HASVALUE 1
#define INCLUDE_PROPERTY_ISUNIFIEDBY 1
#define INCLUDE_PROPERTY_CHARACTERIZES 1
#define INCLUDE_PROPERTY_REST 1
#define INCLUDE_PROPERTY_HASCOMMONBOUNDARY 1
#define INCLUDE_PROPERTY_COPARTICIPATESWITH 1
#define INCLUDE_PROPERTY_ISDEFINEDIN 1
#define INCLUDE_PROPERTY_HASCONSTRAINT 1
#define INCLUDE_PROPERTY_OBSERVEDBY 1
#define INCLUDE_PROPERTY_ISREGIONFOR 1
#define INCLUDE_PROPERTY_OFFEATURE 1
#define INCLUDE_PROPERTY_ISREFERENCEOF 1
#define INCLUDE_PROPERTY_ISCONSTITUENTOF 1
#define INCLUDE_PROPERTY_ISPARAMETERFOR 1
#define INCLUDE_PROPERTY_DIRECTLYPRECEDES 1
#define INCLUDE_PROPERTY_DEFINESROLE 1
#define INCLUDE_PROPERTY_CLASSIFIES 1
#define INCLUDE_PROPERTY_DETECTS 1
#define INCLUDE_PROPERTY_ISCOMPONENTOF 1
#define INCLUDE_PROPERTY_ISSUBORDINATEDTO 1
#define INCLUDE_PROPERTY_ISEXECUTEDIN 1
#define INCLUDE_PROPERTY_ISCONCEPTEXPRESSEDBY 1
#define INCLUDE_PROPERTY_HASREGIONDATAVALUE 1
#define INCLUDE_PROPERTY_HASSURVIVALRANGE 1
#define INCLUDE_PROPERTY_ISTIMEOFOBSERVATIONOF 1
#define INCLUDE_PROPERTY_ISPRODUCEDBY 1
#define INCLUDE_PROPERTY_ISMEMBEROF 1
#define INCLUDE_PROPERTY_ATTACHEDSYSTEM 1
#define INCLUDE_PROPERTY_ISACTIONINCLUDEDIN 1
#define INCLUDE_PROPERTY_ISAGENTINVOLVEDIN 1
#define INCLUDE_PROPERTY_QUALITYOFOBSERVATION 1
#define INCLUDE_PROPERTY_EXECUTESTASK 1
#define INCLUDE_PROPERTY_DESCRIBES 1
#define INCLUDE_PROPERTY_PARAMETRIZES 1
#define INCLUDE_PROPERTY_HASQUALITY 1
#define INCLUDE_PROPERTY_HASDATAVALUE 1
#define INCLUDE_PROPERTY_ISTASKDEFINEDIN 1
#define INCLUDE_PROPERTY_INTRODUCES 1
#define INCLUDE_PROPERTY_ISROLEDEFINEDIN 1
#define INCLUDE_PROPERTY_ISINTRODUCEDBY 1
#define INCLUDE_PROPERTY_ISCONCRETELYEXPRESSEDBY 1
#define INCLUDE_PROPERTY_EXPRESSESCONCEPT 1
#define INCLUDE_PROPERTY_ISCONCEPTUSEDIN 1
#define INCLUDE_PROPERTY_ACTSFOR 1
#define INCLUDE_PROPERTY_VALUE 1
#define INCLUDE_PROPERTY_ISEXPRESSEDBY 1
#define INCLUDE_PROPERTY_ISPARAMETRIZEDBY 1
#define INCLUDE_PROPERTY_OBSERVATIONRESULT 1
#define INCLUDE_PROPERTY_HASROLE 1
#define INCLUDE_PROPERTY_HASLOCATION 1
#define INCLUDE_PROPERTY_INDEPLOYMENT 1
#define INCLUDE_PROPERTY_SATISFIES 1
#define INCLUDE_PROPERTY_INCLUDESOBJECT 1
#define INCLUDE_PROPERTY_OBSERVATIONRESULTTIME 1
#define INCLUDE_PROPERTY_HASEVENTDATE 1
#define INCLUDE_PROPERTY_ISLOCATIONOF 1
#define INCLUDE_PROPERTY_HASTASK 1
#define INCLUDE_PROPERTY_MADEOBSERVATION 1
#define INCLUDE_PROPERTY_DEPLOYEDSYSTEM 1
#define INCLUDE_PROPERTY_ISOBJECTINCLUDEDIN 1
#define INCLUDE_PROPERTY_EXPRESSES 1
#define INCLUDE_PROPERTY_DEFINESTASK 1
#define INCLUDE_PROPERTY_ISCONCEPTUALIZEDBY 1
#define INCLUDE_PROPERTY_HASPARAMETERDATAVALUE 1
#define INCLUDE_PROPERTY_DEPLOYEDONPLATFORM 1
#define INCLUDE_PROPERTY_ISSATISFIEDBY 1
#define INCLUDE_PROPERTY_ISPARTICIPANTIN 1
#define INCLUDE_PROPERTY_HASPART 1
#define INCLUDE_PROPERTY_ISPRECONDITIONOF 1
#define INCLUDE_PROPERTY_ISSETTINGFOR 1
#define INCLUDE_PROPERTY_IMPLEMENTEDBY 1
#define INCLUDE_PROPERTY_ISRELATEDTOCONCEPT 1
#define INCLUDE_CLASS_SOCIALOBJECT 1
#define INCLUDE_CLASS_SYSTEMLIFETIME 1
#define INCLUDE_CLASS_OPERATINGRANGE 1
#define INCLUDE_CLASS_PLACE 1
#define INCLUDE_CLASS_WORKFLOWEXECUTION 1
#define INCLUDE_CLASS_ROLE 1
#define INCLUDE_CLASS_AMOUNT 1
#define INCLUDE_CLASS_PLAINLITERAL 1
#define INCLUDE_CLASS_NARRATIVE 1
#define INCLUDE_CLASS_THEORY 1
#define INCLUDE_CLASS_PROCESS 1
#define INCLUDE_CLASS_OPERATINGPROPERTY 1
#define INCLUDE_CLASS_SITUATION 1
#define INCLUDE_CLASS_ABSTRACT 1
#define INCLUDE_CLASS_SENSORINPUT 1
#define INCLUDE_CLASS_SOCIALPERSON 1
#define INCLUDE_CLASS_SUBSTANCE 1
#define INCLUDE_CLASS_PROPERTY 1
#define INCLUDE_CLASS_GOAL 1
#define INCLUDE_CLASS_PHYSICALARTIFACT 1
#define INCLUDE_CLASS_PROPERTY 1
#define INCLUDE_CLASS_LANGSTRING 1
#define INCLUDE_CLASS_SOCIALRELATION 1
#define INCLUDE_CLASS_OPERATINGPOWERRANGE 1
#define INCLUDE_CLASS_BIOLOGICALOBJECT 1
#define INCLUDE_CLASS_ENTITY 1
#define INCLUDE_CLASS_XMLLITERAL 1
#define INCLUDE_CLASS_DEPLOYMENTRELATEDPROCESS 1
#define INCLUDE_CLASS_TIMEINTERVAL 1
#define INCLUDE_CLASS_SURVIVALRANGE 1
#define INCLUDE_CLASS_DEPLOYMENT 1
#define INCLUDE_CLASS_PRECISION 1
#define INCLUDE_CLASS_SENSOR 1
#define INCLUDE_CLASS_ALT 1
#define INCLUDE_CLASS_FORMALENTITY 1
#define INCLUDE_CLASS_WORKFLOW 1
#define INCLUDE_CLASS_CLASSIFICATION 1
#define INCLUDE_CLASS_OBSERVATIONVALUE 1
#define INCLUDE_CLASS_TRANSITION 1
#define INCLUDE_CLASS_SOCIALAGENT 1
#define INCLUDE_CLASS_FEATUREOFINTEREST 1
#define INCLUDE_CLASS_RESPONSETIME 1
#define INCLUDE_CLASS_EVENT 1
#define INCLUDE_CLASS_STIMULUS 1
#define INCLUDE_CLASS_SENSORDATASHEET 1
#define INCLUDE_CLASS_BATTERYLIFETIME 1
#define INCLUDE_CLASS_SURVIVALPROPERTY 1
#define INCLUDE_CLASS_SYSTEM 1
#define INCLUDE_CLASS_LIST 1
#define INCLUDE_CLASS_PHYSICALAGENT 1
#define INCLUDE_CLASS_MEASUREMENTRANGE 1
#define INCLUDE_CLASS_UNITOFMEASURE 1
#define INCLUDE_CLASS_COLLECTIVE 1
#define INCLUDE_CLASS_OBSERVATION 1
#define INCLUDE_CLASS_QUALITY 1
#define INCLUDE_CLASS_SENSING 1
#define INCLUDE_CLASS_TYPECOLLECTION 1
#define INCLUDE_CLASS_NATURALPERSON 1
#define INCLUDE_CLASS_SENSINGDEVICE 1
#define INCLUDE_CLASS_RIGHT 1
#define INCLUDE_CLASS_CONCEPT 1
#define INCLUDE_CLASS_FREQUENCY 1
#define INCLUDE_CLASS_SELECTIVITY 1
#define INCLUDE_CLASS_CHEMICALOBJECT 1
#define INCLUDE_CLASS_LATENCY 1
#define INCLUDE_CLASS_ORGANIZATION 1
#define INCLUDE_CLASS_SPATIOTEMPORALREGION 1
#define INCLUDE_CLASS_PERSON 1
#define INCLUDE_CLASS_PHYSICALPLACE 1
#define INCLUDE_CLASS_METHOD 1
#define INCLUDE_CLASS_HTML 1
#define INCLUDE_CLASS_DIAGNOSIS 1
#define INCLUDE_CLASS_RESOLUTION 1
#define INCLUDE_CLASS_CLASS 1
#define INCLUDE_CLASS_ACCURACY 1
#define INCLUDE_CLASS_LITERAL 1
#define INCLUDE_CLASS_PLANEXECUTION 1
#define INCLUDE_CLASS_AGENT 1
#define INCLUDE_CLASS_PLAN 1
#define INCLUDE_CLASS_EVENTTYPE 1
#define INCLUDE_CLASS_MAINTENANCESCHEDULE 1
#define INCLUDE_CLASS_DESIGNEDARTIFACT 1
#define INCLUDE_CLASS_STATEMENT 1
#define INCLUDE_CLASS_PROJECT 1
#define INCLUDE_CLASS_MEASUREMENTCAPABILITY 1
#define INCLUDE_CLASS_DESIGNEDSUBSTANCE 1
#define INCLUDE_CLASS_ACTION 1
#define INCLUDE_CLASS_SPACEREGION 1
#define INCLUDE_CLASS_LOCALCONCEPT 1
#define INCLUDE_CLASS_PHYSICALATTRIBUTE 1
#define INCLUDE_CLASS_BAG 1
#define INCLUDE_CLASS_DETECTIONLIMIT 1
#define INCLUDE_CLASS_SENSOROUTPUT 1
#define INCLUDE_CLASS_DEVICE 1
#define INCLUDE_CLASS_TASK 1
#define INCLUDE_CLASS_COLLECTION 1
#define INCLUDE_CLASS_NOTHING 1
#define INCLUDE_CLASS_PERSONIFICATION 1
#define INCLUDE_CLASS_OUTPUT 1
#define INCLUDE_CLASS_RESOURCE 1
#define INCLUDE_CLASS_PHYSICALOBJECT 1
#define INCLUDE_CLASS_RELATION 1
#define INCLUDE_CLASS_SET 1
#define INCLUDE_CLASS_DESIGN 1
#define INCLUDE_CLASS_INPUT 1
#define INCLUDE_CLASS_PROCESS 1
#define INCLUDE_CLASS_ORGANISM 1
#define INCLUDE_CLASS_CONTAINER 1
#define INCLUDE_CLASS_INFORMATIONENTITY 1
#define INCLUDE_CLASS_DRIFT 1
#define INCLUDE_CLASS_MEASUREMENTPROPERTY 1
#define INCLUDE_CLASS_PARAMETER 1
#define INCLUDE_CLASS_PHYSICALBODY 1
#define INCLUDE_CLASS_FUNCTIONALSUBSTANCE 1
#define INCLUDE_CLASS_COLLECTIVEAGENT 1
#define INCLUDE_CLASS_CONDITION 1
#define INCLUDE_CLASS_THING 1
#define INCLUDE_CLASS_INFORMATIONREALIZATION 1
#define INCLUDE_CLASS_PATTERN 1
#define INCLUDE_CLASS_SEQ 1
#define INCLUDE_CLASS_SOCIALOBJECTATTRIBUTE 1
#define INCLUDE_CLASS_REGION 1
#define INCLUDE_CLASS_SENSITIVITY 1
#define INCLUDE_CLASS_COMMUNITY 1
#define INCLUDE_CLASS_DESCRIPTION 1
#define INCLUDE_CLASS_CONTRACT 1
#define INCLUDE_CLASS_PLATFORM 1
#define INCLUDE_CLASS_GROUP 1
#define INCLUDE_CLASS_CONFIGURATION 1
#define INCLUDE_CLASS_OBJECT 1
#define INCLUDE_CLASS_INFORMATIONOBJECT 1
#define INCLUDE_CLASS_NORM 1


#else

#define INCLUDE_PROPERTY_ISEVENTINCLUDEDIN 0
#define INCLUDE_PROPERTY_ISTASKOF 0
#define INCLUDE_PROPERTY_INCLUDESTIME 0
#define INCLUDE_PROPERTY_HASOPERATINGPROPERTY 0
#define INCLUDE_PROPERTY_HASPOSTCONDITION 0
#define INCLUDE_PROPERTY_ISREALIZEDBY 0
#define INCLUDE_PROPERTY_HASMEASUREMENTCAPABILITY 0
#define INCLUDE_PROPERTY_ISCHARACTERIZEDBY 0
#define INCLUDE_PROPERTY_REALIZES 0
#define INCLUDE_PROPERTY_OBJECT 0
#define INCLUDE_PROPERTY_HASINPUT 0
#define INCLUDE_PROPERTY_HASPRECONDITION 0
#define INCLUDE_PROPERTY_INCLUDESEVENT 0
#define INCLUDE_PROPERTY_FORPROPERTY 0
#define INCLUDE_PROPERTY_ISPARTOF 0
#define INCLUDE_PROPERTY_CONCEPTUALIZES 0
#define INCLUDE_PROPERTY_OBSERVES 0
#define INCLUDE_PROPERTY_ISOBSERVABLEAT 0
#define INCLUDE_PROPERTY_IMPLEMENTS 0
#define INCLUDE_PROPERTY_INVOLVESAGENT 0
#define INCLUDE_PROPERTY_ISCOVEREDBY 0
#define INCLUDE_PROPERTY_UNIFIES 0
#define INCLUDE_PROPERTY_DEPLOYMENTPROCESSPART 0
#define INCLUDE_PROPERTY_PREDICATE 0
#define INCLUDE_PROPERTY_CONCRETELYEXPRESSES 0
#define INCLUDE_PROPERTY_OVERLAPS 0
#define INCLUDE_PROPERTY_HASCOMPONENT 0
#define INCLUDE_PROPERTY_ISPROPERTYOF 0
#define INCLUDE_PROPERTY_ISSUPERORDINATEDTO 0
#define INCLUDE_PROPERTY_ISROLEOF 0
#define INCLUDE_PROPERTY_INCLUDESAGENT 0
#define INCLUDE_PROPERTY_ISPOSTCONDITIONOF 0
#define INCLUDE_PROPERTY_OBSERVATIONSAMPLINGTIME 0
#define INCLUDE_PROPERTY_HASOPERATINGRANGE 0
#define INCLUDE_PROPERTY_DIRECTLYFOLLOWS 0
#define INCLUDE_PROPERTY_HASSURVIVALPROPERTY 0
#define INCLUDE_PROPERTY_PRECEDES 0
#define INCLUDE_PROPERTY_HASMEASUREMENTPROPERTY 0
#define INCLUDE_PROPERTY_STARTTIME 0
#define INCLUDE_PROPERTY_EXPANDS 0
#define INCLUDE_PROPERTY_HASSETTING 0
#define INCLUDE_PROPERTY_ISREFERENCEOFINFORMATIONREALIZEDBY 0
#define INCLUDE_PROPERTY_HASSUBSYSTEM 0
#define INCLUDE_PROPERTY_ISEXPANDEDIN 0
#define INCLUDE_PROPERTY_ISRELATEDTODESCRIPTION 0
#define INCLUDE_PROPERTY_ISCONSTRAINTFOR 0
#define INCLUDE_PROPERTY_HASREGION 0
#define INCLUDE_PROPERTY_NEARTO 0
#define INCLUDE_PROPERTY_HASPROPERTY 0
#define INCLUDE_PROPERTY_FARFROM 0
#define INCLUDE_PROPERTY_FOLLOWS 0
#define INCLUDE_PROPERTY_ISDESCRIBEDBY 0
#define INCLUDE_PROPERTY_ISPROXYFOR 0
#define INCLUDE_PROPERTY_ISTIMEINCLUDEDIN 0
#define INCLUDE_PROPERTY_SPECIALIZES 0
#define INCLUDE_PROPERTY_ACTSTHROUGH 0
#define INCLUDE_PROPERTY_INCONDITION 0
#define INCLUDE_PROPERTY_HASDEPLOYMENT 0
#define INCLUDE_PROPERTY_INCLUDESACTION 0
#define INCLUDE_PROPERTY_FIRST 0
#define INCLUDE_PROPERTY_HASPARAMETER 0
#define INCLUDE_PROPERTY_HASMEMBER 0
#define INCLUDE_PROPERTY_HASCONSTITUENT 0
#define INCLUDE_PROPERTY_FEATUREOFINTEREST 0
#define INCLUDE_PROPERTY_ENDTIME 0
#define INCLUDE_PROPERTY_ISAGENTINCLUDEDIN 0
#define INCLUDE_PROPERTY_OBSERVEDPROPERTY 0
#define INCLUDE_PROPERTY_ISCLASSIFIEDBY 0
#define INCLUDE_PROPERTY_COVERS 0
#define INCLUDE_PROPERTY_ONPLATFORM 0
#define INCLUDE_PROPERTY_HASPROXY 0
#define INCLUDE_PROPERTY_HASINTERVALDATE 0
#define INCLUDE_PROPERTY_SENSINGMETHODUSED 0
#define INCLUDE_PROPERTY_HASPARTICIPANT 0
#define INCLUDE_PROPERTY_ISQUALITYOF 0
#define INCLUDE_PROPERTY_ISABOUT 0
#define INCLUDE_PROPERTY_USESCONCEPT 0
#define INCLUDE_PROPERTY_HASOUTPUT 0
#define INCLUDE_PROPERTY_ISSPECIALIZEDBY 0
#define INCLUDE_PROPERTY_DEFINES 0
#define INCLUDE_PROPERTY_REALIZESINFORMATIONABOUT 0
#define INCLUDE_PROPERTY_HASVALUE 0
#define INCLUDE_PROPERTY_ISUNIFIEDBY 0
#define INCLUDE_PROPERTY_CHARACTERIZES 0
#define INCLUDE_PROPERTY_REST 0
#define INCLUDE_PROPERTY_HASCOMMONBOUNDARY 0
#define INCLUDE_PROPERTY_COPARTICIPATESWITH 0
#define INCLUDE_PROPERTY_ISDEFINEDIN 0
#define INCLUDE_PROPERTY_HASCONSTRAINT 0
#define INCLUDE_PROPERTY_OBSERVEDBY 0
#define INCLUDE_PROPERTY_ISREGIONFOR 0
#define INCLUDE_PROPERTY_OFFEATURE 0
#define INCLUDE_PROPERTY_ISREFERENCEOF 0
#define INCLUDE_PROPERTY_ISCONSTITUENTOF 0
#define INCLUDE_PROPERTY_ISPARAMETERFOR 0
#define INCLUDE_PROPERTY_DIRECTLYPRECEDES 0
#define INCLUDE_PROPERTY_DEFINESROLE 0
#define INCLUDE_PROPERTY_CLASSIFIES 0
#define INCLUDE_PROPERTY_DETECTS 0
#define INCLUDE_PROPERTY_ISCOMPONENTOF 0
#define INCLUDE_PROPERTY_ISSUBORDINATEDTO 0
#define INCLUDE_PROPERTY_ISEXECUTEDIN 0
#define INCLUDE_PROPERTY_ISCONCEPTEXPRESSEDBY 0
#define INCLUDE_PROPERTY_HASREGIONDATAVALUE 0
#define INCLUDE_PROPERTY_HASSURVIVALRANGE 0
#define INCLUDE_PROPERTY_ISTIMEOFOBSERVATIONOF 0
#define INCLUDE_PROPERTY_ISPRODUCEDBY 0
#define INCLUDE_PROPERTY_ISMEMBEROF 0
#define INCLUDE_PROPERTY_ATTACHEDSYSTEM 0
#define INCLUDE_PROPERTY_ISACTIONINCLUDEDIN 0
#define INCLUDE_PROPERTY_ISAGENTINVOLVEDIN 0
#define INCLUDE_PROPERTY_QUALITYOFOBSERVATION 0
#define INCLUDE_PROPERTY_EXECUTESTASK 0
#define INCLUDE_PROPERTY_DESCRIBES 0
#define INCLUDE_PROPERTY_PARAMETRIZES 0
#define INCLUDE_PROPERTY_HASQUALITY 0
#define INCLUDE_PROPERTY_HASDATAVALUE 0
#define INCLUDE_PROPERTY_ISTASKDEFINEDIN 0
#define INCLUDE_PROPERTY_INTRODUCES 0
#define INCLUDE_PROPERTY_ISROLEDEFINEDIN 0
#define INCLUDE_PROPERTY_ISINTRODUCEDBY 0
#define INCLUDE_PROPERTY_ISCONCRETELYEXPRESSEDBY 0
#define INCLUDE_PROPERTY_EXPRESSESCONCEPT 0
#define INCLUDE_PROPERTY_ISCONCEPTUSEDIN 0
#define INCLUDE_PROPERTY_ACTSFOR 0
#define INCLUDE_PROPERTY_VALUE 0
#define INCLUDE_PROPERTY_ISEXPRESSEDBY 0
#define INCLUDE_PROPERTY_ISPARAMETRIZEDBY 0
#define INCLUDE_PROPERTY_OBSERVATIONRESULT 0
#define INCLUDE_PROPERTY_HASROLE 0
#define INCLUDE_PROPERTY_HASLOCATION 0
#define INCLUDE_PROPERTY_INDEPLOYMENT 0
#define INCLUDE_PROPERTY_SATISFIES 0
#define INCLUDE_PROPERTY_INCLUDESOBJECT 0
#define INCLUDE_PROPERTY_OBSERVATIONRESULTTIME 0
#define INCLUDE_PROPERTY_HASEVENTDATE 0
#define INCLUDE_PROPERTY_ISLOCATIONOF 0
#define INCLUDE_PROPERTY_HASTASK 0
#define INCLUDE_PROPERTY_MADEOBSERVATION 0
#define INCLUDE_PROPERTY_DEPLOYEDSYSTEM 0
#define INCLUDE_PROPERTY_ISOBJECTINCLUDEDIN 0
#define INCLUDE_PROPERTY_EXPRESSES 0
#define INCLUDE_PROPERTY_DEFINESTASK 0
#define INCLUDE_PROPERTY_ISCONCEPTUALIZEDBY 0
#define INCLUDE_PROPERTY_HASPARAMETERDATAVALUE 0
#define INCLUDE_PROPERTY_DEPLOYEDONPLATFORM 0
#define INCLUDE_PROPERTY_ISSATISFIEDBY 0
#define INCLUDE_PROPERTY_ISPARTICIPANTIN 0
#define INCLUDE_PROPERTY_HASPART 0
#define INCLUDE_PROPERTY_ISPRECONDITIONOF 0
#define INCLUDE_PROPERTY_ISSETTINGFOR 0
#define INCLUDE_PROPERTY_IMPLEMENTEDBY 0
#define INCLUDE_PROPERTY_ISRELATEDTOCONCEPT 0
#define INCLUDE_CLASS_SOCIALOBJECT 0
#define INCLUDE_CLASS_SYSTEMLIFETIME 0
#define INCLUDE_CLASS_OPERATINGRANGE 0
#define INCLUDE_CLASS_PLACE 0
#define INCLUDE_CLASS_WORKFLOWEXECUTION 0
#define INCLUDE_CLASS_ROLE 0
#define INCLUDE_CLASS_AMOUNT 0
#define INCLUDE_CLASS_PLAINLITERAL 0
#define INCLUDE_CLASS_NARRATIVE 0
#define INCLUDE_CLASS_THEORY 0
#define INCLUDE_CLASS_PROCESS 0
#define INCLUDE_CLASS_OPERATINGPROPERTY 0
#define INCLUDE_CLASS_SITUATION 0
#define INCLUDE_CLASS_ABSTRACT 0
#define INCLUDE_CLASS_SENSORINPUT 0
#define INCLUDE_CLASS_SOCIALPERSON 0
#define INCLUDE_CLASS_SUBSTANCE 0
#define INCLUDE_CLASS_PROPERTY 0
#define INCLUDE_CLASS_GOAL 0
#define INCLUDE_CLASS_PHYSICALARTIFACT 0
#define INCLUDE_CLASS_PROPERTY 0
#define INCLUDE_CLASS_LANGSTRING 0
#define INCLUDE_CLASS_SOCIALRELATION 0
#define INCLUDE_CLASS_OPERATINGPOWERRANGE 0
#define INCLUDE_CLASS_BIOLOGICALOBJECT 0
#define INCLUDE_CLASS_ENTITY 0
#define INCLUDE_CLASS_XMLLITERAL 0
#define INCLUDE_CLASS_DEPLOYMENTRELATEDPROCESS 0
#define INCLUDE_CLASS_TIMEINTERVAL 0
#define INCLUDE_CLASS_SURVIVALRANGE 0
#define INCLUDE_CLASS_DEPLOYMENT 0
#define INCLUDE_CLASS_PRECISION 0
#define INCLUDE_CLASS_SENSOR 0
#define INCLUDE_CLASS_ALT 0
#define INCLUDE_CLASS_FORMALENTITY 0
#define INCLUDE_CLASS_WORKFLOW 0
#define INCLUDE_CLASS_CLASSIFICATION 0
#define INCLUDE_CLASS_OBSERVATIONVALUE 0
#define INCLUDE_CLASS_TRANSITION 0
#define INCLUDE_CLASS_SOCIALAGENT 0
#define INCLUDE_CLASS_FEATUREOFINTEREST 0
#define INCLUDE_CLASS_RESPONSETIME 0
#define INCLUDE_CLASS_EVENT 0
#define INCLUDE_CLASS_STIMULUS 0
#define INCLUDE_CLASS_SENSORDATASHEET 0
#define INCLUDE_CLASS_BATTERYLIFETIME 0
#define INCLUDE_CLASS_SURVIVALPROPERTY 0
#define INCLUDE_CLASS_SYSTEM 0
#define INCLUDE_CLASS_LIST 0
#define INCLUDE_CLASS_PHYSICALAGENT 0
#define INCLUDE_CLASS_MEASUREMENTRANGE 0
#define INCLUDE_CLASS_UNITOFMEASURE 0
#define INCLUDE_CLASS_COLLECTIVE 0
#define INCLUDE_CLASS_OBSERVATION 0
#define INCLUDE_CLASS_QUALITY 0
#define INCLUDE_CLASS_SENSING 0
#define INCLUDE_CLASS_TYPECOLLECTION 0
#define INCLUDE_CLASS_NATURALPERSON 0
#define INCLUDE_CLASS_SENSINGDEVICE 0
#define INCLUDE_CLASS_RIGHT 0
#define INCLUDE_CLASS_CONCEPT 0
#define INCLUDE_CLASS_FREQUENCY 0
#define INCLUDE_CLASS_SELECTIVITY 0
#define INCLUDE_CLASS_CHEMICALOBJECT 0
#define INCLUDE_CLASS_LATENCY 0
#define INCLUDE_CLASS_ORGANIZATION 0
#define INCLUDE_CLASS_SPATIOTEMPORALREGION 0
#define INCLUDE_CLASS_PERSON 0
#define INCLUDE_CLASS_PHYSICALPLACE 0
#define INCLUDE_CLASS_METHOD 0
#define INCLUDE_CLASS_HTML 0
#define INCLUDE_CLASS_DIAGNOSIS 0
#define INCLUDE_CLASS_RESOLUTION 0
#define INCLUDE_CLASS_CLASS 0
#define INCLUDE_CLASS_ACCURACY 0
#define INCLUDE_CLASS_LITERAL 0
#define INCLUDE_CLASS_PLANEXECUTION 0
#define INCLUDE_CLASS_AGENT 0
#define INCLUDE_CLASS_PLAN 0
#define INCLUDE_CLASS_EVENTTYPE 0
#define INCLUDE_CLASS_MAINTENANCESCHEDULE 0
#define INCLUDE_CLASS_DESIGNEDARTIFACT 0
#define INCLUDE_CLASS_STATEMENT 0
#define INCLUDE_CLASS_PROJECT 0
#define INCLUDE_CLASS_MEASUREMENTCAPABILITY 0
#define INCLUDE_CLASS_DESIGNEDSUBSTANCE 0
#define INCLUDE_CLASS_ACTION 0
#define INCLUDE_CLASS_SPACEREGION 0
#define INCLUDE_CLASS_LOCALCONCEPT 0
#define INCLUDE_CLASS_PHYSICALATTRIBUTE 0
#define INCLUDE_CLASS_BAG 0
#define INCLUDE_CLASS_DETECTIONLIMIT 0
#define INCLUDE_CLASS_SENSOROUTPUT 0
#define INCLUDE_CLASS_DEVICE 0
#define INCLUDE_CLASS_TASK 0
#define INCLUDE_CLASS_COLLECTION 0
#define INCLUDE_CLASS_NOTHING 0
#define INCLUDE_CLASS_PERSONIFICATION 0
#define INCLUDE_CLASS_OUTPUT 0
#define INCLUDE_CLASS_RESOURCE 0
#define INCLUDE_CLASS_PHYSICALOBJECT 0
#define INCLUDE_CLASS_RELATION 0
#define INCLUDE_CLASS_SET 0
#define INCLUDE_CLASS_DESIGN 0
#define INCLUDE_CLASS_INPUT 0
#define INCLUDE_CLASS_PROCESS 0
#define INCLUDE_CLASS_ORGANISM 0
#define INCLUDE_CLASS_CONTAINER 0
#define INCLUDE_CLASS_INFORMATIONENTITY 0
#define INCLUDE_CLASS_DRIFT 0
#define INCLUDE_CLASS_MEASUREMENTPROPERTY 0
#define INCLUDE_CLASS_PARAMETER 0
#define INCLUDE_CLASS_PHYSICALBODY 0
#define INCLUDE_CLASS_FUNCTIONALSUBSTANCE 0
#define INCLUDE_CLASS_COLLECTIVEAGENT 0
#define INCLUDE_CLASS_CONDITION 0
#define INCLUDE_CLASS_THING 0
#define INCLUDE_CLASS_INFORMATIONREALIZATION 0
#define INCLUDE_CLASS_PATTERN 0
#define INCLUDE_CLASS_SEQ 0
#define INCLUDE_CLASS_SOCIALOBJECTATTRIBUTE 0
#define INCLUDE_CLASS_REGION 0
#define INCLUDE_CLASS_SENSITIVITY 0
#define INCLUDE_CLASS_COMMUNITY 0
#define INCLUDE_CLASS_DESCRIPTION 0
#define INCLUDE_CLASS_CONTRACT 0
#define INCLUDE_CLASS_PLATFORM 0
#define INCLUDE_CLASS_GROUP 0
#define INCLUDE_CLASS_CONFIGURATION 0
#define INCLUDE_CLASS_OBJECT 0
#define INCLUDE_CLASS_INFORMATIONOBJECT 0
#define INCLUDE_CLASS_NORM 0


#endif


#if INCLUDE_CLASS_SOCIALOBJECT
extern class_t *CLASS_SOCIALOBJECT;
#endif
#if INCLUDE_CLASS_SYSTEMLIFETIME
extern class_t *CLASS_SYSTEMLIFETIME;
#endif
#if INCLUDE_CLASS_OPERATINGRANGE
extern class_t *CLASS_OPERATINGRANGE;
#endif
#if INCLUDE_CLASS_PLACE
extern class_t *CLASS_PLACE;
#endif
#if INCLUDE_CLASS_WORKFLOWEXECUTION
extern class_t *CLASS_WORKFLOWEXECUTION;
#endif
#if INCLUDE_CLASS_ROLE
extern class_t *CLASS_ROLE;
#endif
#if INCLUDE_CLASS_AMOUNT
extern class_t *CLASS_AMOUNT;
#endif
#if INCLUDE_CLASS_PLAINLITERAL
extern class_t *CLASS_PLAINLITERAL;
#endif
#if INCLUDE_CLASS_NARRATIVE
extern class_t *CLASS_NARRATIVE;
#endif
#if INCLUDE_CLASS_THEORY
extern class_t *CLASS_THEORY;
#endif
#if INCLUDE_CLASS_PROCESS
extern class_t *CLASS_PROCESS;
#endif
#if INCLUDE_CLASS_OPERATINGPROPERTY
extern class_t *CLASS_OPERATINGPROPERTY;
#endif
#if INCLUDE_CLASS_SITUATION
extern class_t *CLASS_SITUATION;
#endif
#if INCLUDE_CLASS_ABSTRACT
extern class_t *CLASS_ABSTRACT;
#endif
#if INCLUDE_CLASS_SENSORINPUT
extern class_t *CLASS_SENSORINPUT;
#endif
#if INCLUDE_CLASS_SOCIALPERSON
extern class_t *CLASS_SOCIALPERSON;
#endif
#if INCLUDE_CLASS_SUBSTANCE
extern class_t *CLASS_SUBSTANCE;
#endif
#if INCLUDE_CLASS_PROPERTY
extern class_t *CLASS_PROPERTY;
#endif
#if INCLUDE_CLASS_GOAL
extern class_t *CLASS_GOAL;
#endif
#if INCLUDE_CLASS_PHYSICALARTIFACT
extern class_t *CLASS_PHYSICALARTIFACT;
#endif
#if INCLUDE_CLASS_PROPERTY
extern class_t *CLASS_PROPERTY;
#endif
#if INCLUDE_CLASS_LANGSTRING
extern class_t *CLASS_LANGSTRING;
#endif
#if INCLUDE_CLASS_SOCIALRELATION
extern class_t *CLASS_SOCIALRELATION;
#endif
#if INCLUDE_CLASS_OPERATINGPOWERRANGE
extern class_t *CLASS_OPERATINGPOWERRANGE;
#endif
#if INCLUDE_CLASS_BIOLOGICALOBJECT
extern class_t *CLASS_BIOLOGICALOBJECT;
#endif
#if INCLUDE_CLASS_ENTITY
extern class_t *CLASS_ENTITY;
#endif
#if INCLUDE_CLASS_XMLLITERAL
extern class_t *CLASS_XMLLITERAL;
#endif
#if INCLUDE_CLASS_DEPLOYMENTRELATEDPROCESS
extern class_t *CLASS_DEPLOYMENTRELATEDPROCESS;
#endif
#if INCLUDE_CLASS_TIMEINTERVAL
extern class_t *CLASS_TIMEINTERVAL;
#endif
#if INCLUDE_CLASS_SURVIVALRANGE
extern class_t *CLASS_SURVIVALRANGE;
#endif
#if INCLUDE_CLASS_DEPLOYMENT
extern class_t *CLASS_DEPLOYMENT;
#endif
#if INCLUDE_CLASS_PRECISION
extern class_t *CLASS_PRECISION;
#endif
#if INCLUDE_CLASS_SENSOR
extern class_t *CLASS_SENSOR;
#endif
#if INCLUDE_CLASS_ALT
extern class_t *CLASS_ALT;
#endif
#if INCLUDE_CLASS_FORMALENTITY
extern class_t *CLASS_FORMALENTITY;
#endif
#if INCLUDE_CLASS_WORKFLOW
extern class_t *CLASS_WORKFLOW;
#endif
#if INCLUDE_CLASS_CLASSIFICATION
extern class_t *CLASS_CLASSIFICATION;
#endif
#if INCLUDE_CLASS_OBSERVATIONVALUE
extern class_t *CLASS_OBSERVATIONVALUE;
#endif
#if INCLUDE_CLASS_TRANSITION
extern class_t *CLASS_TRANSITION;
#endif
#if INCLUDE_CLASS_SOCIALAGENT
extern class_t *CLASS_SOCIALAGENT;
#endif
#if INCLUDE_CLASS_FEATUREOFINTEREST
extern class_t *CLASS_FEATUREOFINTEREST;
#endif
#if INCLUDE_CLASS_RESPONSETIME
extern class_t *CLASS_RESPONSETIME;
#endif
#if INCLUDE_CLASS_EVENT
extern class_t *CLASS_EVENT;
#endif
#if INCLUDE_CLASS_STIMULUS
extern class_t *CLASS_STIMULUS;
#endif
#if INCLUDE_CLASS_SENSORDATASHEET
extern class_t *CLASS_SENSORDATASHEET;
#endif
#if INCLUDE_CLASS_BATTERYLIFETIME
extern class_t *CLASS_BATTERYLIFETIME;
#endif
#if INCLUDE_CLASS_SURVIVALPROPERTY
extern class_t *CLASS_SURVIVALPROPERTY;
#endif
#if INCLUDE_CLASS_SYSTEM
extern class_t *CLASS_SYSTEM;
#endif
#if INCLUDE_CLASS_LIST
extern class_t *CLASS_LIST;
#endif
#if INCLUDE_CLASS_PHYSICALAGENT
extern class_t *CLASS_PHYSICALAGENT;
#endif
#if INCLUDE_CLASS_MEASUREMENTRANGE
extern class_t *CLASS_MEASUREMENTRANGE;
#endif
#if INCLUDE_CLASS_UNITOFMEASURE
extern class_t *CLASS_UNITOFMEASURE;
#endif
#if INCLUDE_CLASS_COLLECTIVE
extern class_t *CLASS_COLLECTIVE;
#endif
#if INCLUDE_CLASS_OBSERVATION
extern class_t *CLASS_OBSERVATION;
#endif
#if INCLUDE_CLASS_QUALITY
extern class_t *CLASS_QUALITY;
#endif
#if INCLUDE_CLASS_SENSING
extern class_t *CLASS_SENSING;
#endif
#if INCLUDE_CLASS_TYPECOLLECTION
extern class_t *CLASS_TYPECOLLECTION;
#endif
#if INCLUDE_CLASS_NATURALPERSON
extern class_t *CLASS_NATURALPERSON;
#endif
#if INCLUDE_CLASS_SENSINGDEVICE
extern class_t *CLASS_SENSINGDEVICE;
#endif
#if INCLUDE_CLASS_RIGHT
extern class_t *CLASS_RIGHT;
#endif
#if INCLUDE_CLASS_CONCEPT
extern class_t *CLASS_CONCEPT;
#endif
#if INCLUDE_CLASS_FREQUENCY
extern class_t *CLASS_FREQUENCY;
#endif
#if INCLUDE_CLASS_SELECTIVITY
extern class_t *CLASS_SELECTIVITY;
#endif
#if INCLUDE_CLASS_CHEMICALOBJECT
extern class_t *CLASS_CHEMICALOBJECT;
#endif
#if INCLUDE_CLASS_LATENCY
extern class_t *CLASS_LATENCY;
#endif
#if INCLUDE_CLASS_ORGANIZATION
extern class_t *CLASS_ORGANIZATION;
#endif
#if INCLUDE_CLASS_SPATIOTEMPORALREGION
extern class_t *CLASS_SPATIOTEMPORALREGION;
#endif
#if INCLUDE_CLASS_PERSON
extern class_t *CLASS_PERSON;
#endif
#if INCLUDE_CLASS_PHYSICALPLACE
extern class_t *CLASS_PHYSICALPLACE;
#endif
#if INCLUDE_CLASS_METHOD
extern class_t *CLASS_METHOD;
#endif
#if INCLUDE_CLASS_HTML
extern class_t *CLASS_HTML;
#endif
#if INCLUDE_CLASS_DIAGNOSIS
extern class_t *CLASS_DIAGNOSIS;
#endif
#if INCLUDE_CLASS_RESOLUTION
extern class_t *CLASS_RESOLUTION;
#endif
#if INCLUDE_CLASS_CLASS
extern class_t *CLASS_CLASS;
#endif
#if INCLUDE_CLASS_ACCURACY
extern class_t *CLASS_ACCURACY;
#endif
#if INCLUDE_CLASS_LITERAL
extern class_t *CLASS_LITERAL;
#endif
#if INCLUDE_CLASS_PLANEXECUTION
extern class_t *CLASS_PLANEXECUTION;
#endif
#if INCLUDE_CLASS_AGENT
extern class_t *CLASS_AGENT;
#endif
#if INCLUDE_CLASS_PLAN
extern class_t *CLASS_PLAN;
#endif
#if INCLUDE_CLASS_EVENTTYPE
extern class_t *CLASS_EVENTTYPE;
#endif
#if INCLUDE_CLASS_MAINTENANCESCHEDULE
extern class_t *CLASS_MAINTENANCESCHEDULE;
#endif
#if INCLUDE_CLASS_DESIGNEDARTIFACT
extern class_t *CLASS_DESIGNEDARTIFACT;
#endif
#if INCLUDE_CLASS_STATEMENT
extern class_t *CLASS_STATEMENT;
#endif
#if INCLUDE_CLASS_PROJECT
extern class_t *CLASS_PROJECT;
#endif
#if INCLUDE_CLASS_MEASUREMENTCAPABILITY
extern class_t *CLASS_MEASUREMENTCAPABILITY;
#endif
#if INCLUDE_CLASS_DESIGNEDSUBSTANCE
extern class_t *CLASS_DESIGNEDSUBSTANCE;
#endif
#if INCLUDE_CLASS_ACTION
extern class_t *CLASS_ACTION;
#endif
#if INCLUDE_CLASS_SPACEREGION
extern class_t *CLASS_SPACEREGION;
#endif
#if INCLUDE_CLASS_LOCALCONCEPT
extern class_t *CLASS_LOCALCONCEPT;
#endif
#if INCLUDE_CLASS_PHYSICALATTRIBUTE
extern class_t *CLASS_PHYSICALATTRIBUTE;
#endif
#if INCLUDE_CLASS_BAG
extern class_t *CLASS_BAG;
#endif
#if INCLUDE_CLASS_DETECTIONLIMIT
extern class_t *CLASS_DETECTIONLIMIT;
#endif
#if INCLUDE_CLASS_SENSOROUTPUT
extern class_t *CLASS_SENSOROUTPUT;
#endif
#if INCLUDE_CLASS_DEVICE
extern class_t *CLASS_DEVICE;
#endif
#if INCLUDE_CLASS_TASK
extern class_t *CLASS_TASK;
#endif
#if INCLUDE_CLASS_COLLECTION
extern class_t *CLASS_COLLECTION;
#endif
#if INCLUDE_CLASS_NOTHING
extern class_t *CLASS_NOTHING;
#endif
#if INCLUDE_CLASS_PERSONIFICATION
extern class_t *CLASS_PERSONIFICATION;
#endif
#if INCLUDE_CLASS_OUTPUT
extern class_t *CLASS_OUTPUT;
#endif
#if INCLUDE_CLASS_RESOURCE
extern class_t *CLASS_RESOURCE;
#endif
#if INCLUDE_CLASS_PHYSICALOBJECT
extern class_t *CLASS_PHYSICALOBJECT;
#endif
#if INCLUDE_CLASS_RELATION
extern class_t *CLASS_RELATION;
#endif
#if INCLUDE_CLASS_SET
extern class_t *CLASS_SET;
#endif
#if INCLUDE_CLASS_DESIGN
extern class_t *CLASS_DESIGN;
#endif
#if INCLUDE_CLASS_INPUT
extern class_t *CLASS_INPUT;
#endif
#if INCLUDE_CLASS_PROCESS
extern class_t *CLASS_PROCESS;
#endif
#if INCLUDE_CLASS_ORGANISM
extern class_t *CLASS_ORGANISM;
#endif
#if INCLUDE_CLASS_CONTAINER
extern class_t *CLASS_CONTAINER;
#endif
#if INCLUDE_CLASS_INFORMATIONENTITY
extern class_t *CLASS_INFORMATIONENTITY;
#endif
#if INCLUDE_CLASS_DRIFT
extern class_t *CLASS_DRIFT;
#endif
#if INCLUDE_CLASS_MEASUREMENTPROPERTY
extern class_t *CLASS_MEASUREMENTPROPERTY;
#endif
#if INCLUDE_CLASS_PARAMETER
extern class_t *CLASS_PARAMETER;
#endif
#if INCLUDE_CLASS_PHYSICALBODY
extern class_t *CLASS_PHYSICALBODY;
#endif
#if INCLUDE_CLASS_FUNCTIONALSUBSTANCE
extern class_t *CLASS_FUNCTIONALSUBSTANCE;
#endif
#if INCLUDE_CLASS_COLLECTIVEAGENT
extern class_t *CLASS_COLLECTIVEAGENT;
#endif
#if INCLUDE_CLASS_CONDITION
extern class_t *CLASS_CONDITION;
#endif
#if INCLUDE_CLASS_THING
extern class_t *CLASS_THING;
#endif
#if INCLUDE_CLASS_INFORMATIONREALIZATION
extern class_t *CLASS_INFORMATIONREALIZATION;
#endif
#if INCLUDE_CLASS_PATTERN
extern class_t *CLASS_PATTERN;
#endif
#if INCLUDE_CLASS_SEQ
extern class_t *CLASS_SEQ;
#endif
#if INCLUDE_CLASS_SOCIALOBJECTATTRIBUTE
extern class_t *CLASS_SOCIALOBJECTATTRIBUTE;
#endif
#if INCLUDE_CLASS_REGION
extern class_t *CLASS_REGION;
#endif
#if INCLUDE_CLASS_SENSITIVITY
extern class_t *CLASS_SENSITIVITY;
#endif
#if INCLUDE_CLASS_COMMUNITY
extern class_t *CLASS_COMMUNITY;
#endif
#if INCLUDE_CLASS_DESCRIPTION
extern class_t *CLASS_DESCRIPTION;
#endif
#if INCLUDE_CLASS_CONTRACT
extern class_t *CLASS_CONTRACT;
#endif
#if INCLUDE_CLASS_PLATFORM
extern class_t *CLASS_PLATFORM;
#endif
#if INCLUDE_CLASS_GROUP
extern class_t *CLASS_GROUP;
#endif
#if INCLUDE_CLASS_CONFIGURATION
extern class_t *CLASS_CONFIGURATION;
#endif
#if INCLUDE_CLASS_OBJECT
extern class_t *CLASS_OBJECT;
#endif
#if INCLUDE_CLASS_INFORMATIONOBJECT
extern class_t *CLASS_INFORMATIONOBJECT;
#endif
#if INCLUDE_CLASS_NORM
extern class_t *CLASS_NORM;
#endif


#if INCLUDE_PROPERTY_ISEVENTINCLUDEDIN
extern property_t *PROPERTY_ISEVENTINCLUDEDIN;
#endif
#if INCLUDE_PROPERTY_ISTASKOF
extern property_t *PROPERTY_ISTASKOF;
#endif
#if INCLUDE_PROPERTY_INCLUDESTIME
extern property_t *PROPERTY_INCLUDESTIME;
#endif
#if INCLUDE_PROPERTY_HASOPERATINGPROPERTY
extern property_t *PROPERTY_HASOPERATINGPROPERTY;
#endif
#if INCLUDE_PROPERTY_HASPOSTCONDITION
extern property_t *PROPERTY_HASPOSTCONDITION;
#endif
#if INCLUDE_PROPERTY_ISREALIZEDBY
extern property_t *PROPERTY_ISREALIZEDBY;
#endif
#if INCLUDE_PROPERTY_HASMEASUREMENTCAPABILITY
extern property_t *PROPERTY_HASMEASUREMENTCAPABILITY;
#endif
#if INCLUDE_PROPERTY_ISCHARACTERIZEDBY
extern property_t *PROPERTY_ISCHARACTERIZEDBY;
#endif
#if INCLUDE_PROPERTY_REALIZES
extern property_t *PROPERTY_REALIZES;
#endif
#if INCLUDE_PROPERTY_OBJECT
extern property_t *PROPERTY_OBJECT;
#endif
#if INCLUDE_PROPERTY_HASINPUT
extern property_t *PROPERTY_HASINPUT;
#endif
#if INCLUDE_PROPERTY_HASPRECONDITION
extern property_t *PROPERTY_HASPRECONDITION;
#endif
#if INCLUDE_PROPERTY_INCLUDESEVENT
extern property_t *PROPERTY_INCLUDESEVENT;
#endif
#if INCLUDE_PROPERTY_FORPROPERTY
extern property_t *PROPERTY_FORPROPERTY;
#endif
#if INCLUDE_PROPERTY_ISPARTOF
extern property_t *PROPERTY_ISPARTOF;
#endif
#if INCLUDE_PROPERTY_CONCEPTUALIZES
extern property_t *PROPERTY_CONCEPTUALIZES;
#endif
#if INCLUDE_PROPERTY_OBSERVES
extern property_t *PROPERTY_OBSERVES;
#endif
#if INCLUDE_PROPERTY_ISOBSERVABLEAT
extern property_t *PROPERTY_ISOBSERVABLEAT;
#endif
#if INCLUDE_PROPERTY_IMPLEMENTS
extern property_t *PROPERTY_IMPLEMENTS;
#endif
#if INCLUDE_PROPERTY_INVOLVESAGENT
extern property_t *PROPERTY_INVOLVESAGENT;
#endif
#if INCLUDE_PROPERTY_ISCOVEREDBY
extern property_t *PROPERTY_ISCOVEREDBY;
#endif
#if INCLUDE_PROPERTY_UNIFIES
extern property_t *PROPERTY_UNIFIES;
#endif
#if INCLUDE_PROPERTY_DEPLOYMENTPROCESSPART
extern property_t *PROPERTY_DEPLOYMENTPROCESSPART;
#endif
#if INCLUDE_PROPERTY_PREDICATE
extern property_t *PROPERTY_PREDICATE;
#endif
#if INCLUDE_PROPERTY_CONCRETELYEXPRESSES
extern property_t *PROPERTY_CONCRETELYEXPRESSES;
#endif
#if INCLUDE_PROPERTY_OVERLAPS
extern property_t *PROPERTY_OVERLAPS;
#endif
#if INCLUDE_PROPERTY_HASCOMPONENT
extern property_t *PROPERTY_HASCOMPONENT;
#endif
#if INCLUDE_PROPERTY_ISPROPERTYOF
extern property_t *PROPERTY_ISPROPERTYOF;
#endif
#if INCLUDE_PROPERTY_ISSUPERORDINATEDTO
extern property_t *PROPERTY_ISSUPERORDINATEDTO;
#endif
#if INCLUDE_PROPERTY_ISROLEOF
extern property_t *PROPERTY_ISROLEOF;
#endif
#if INCLUDE_PROPERTY_INCLUDESAGENT
extern property_t *PROPERTY_INCLUDESAGENT;
#endif
#if INCLUDE_PROPERTY_ISPOSTCONDITIONOF
extern property_t *PROPERTY_ISPOSTCONDITIONOF;
#endif
#if INCLUDE_PROPERTY_OBSERVATIONSAMPLINGTIME
extern property_t *PROPERTY_OBSERVATIONSAMPLINGTIME;
#endif
#if INCLUDE_PROPERTY_HASOPERATINGRANGE
extern property_t *PROPERTY_HASOPERATINGRANGE;
#endif
#if INCLUDE_PROPERTY_DIRECTLYFOLLOWS
extern property_t *PROPERTY_DIRECTLYFOLLOWS;
#endif
#if INCLUDE_PROPERTY_HASSURVIVALPROPERTY
extern property_t *PROPERTY_HASSURVIVALPROPERTY;
#endif
#if INCLUDE_PROPERTY_PRECEDES
extern property_t *PROPERTY_PRECEDES;
#endif
#if INCLUDE_PROPERTY_HASMEASUREMENTPROPERTY
extern property_t *PROPERTY_HASMEASUREMENTPROPERTY;
#endif
#if INCLUDE_PROPERTY_STARTTIME
extern property_t *PROPERTY_STARTTIME;
#endif
#if INCLUDE_PROPERTY_EXPANDS
extern property_t *PROPERTY_EXPANDS;
#endif
#if INCLUDE_PROPERTY_HASSETTING
extern property_t *PROPERTY_HASSETTING;
#endif
#if INCLUDE_PROPERTY_ISREFERENCEOFINFORMATIONREALIZEDBY
extern property_t *PROPERTY_ISREFERENCEOFINFORMATIONREALIZEDBY;
#endif
#if INCLUDE_PROPERTY_HASSUBSYSTEM
extern property_t *PROPERTY_HASSUBSYSTEM;
#endif
#if INCLUDE_PROPERTY_ISEXPANDEDIN
extern property_t *PROPERTY_ISEXPANDEDIN;
#endif
#if INCLUDE_PROPERTY_ISRELATEDTODESCRIPTION
extern property_t *PROPERTY_ISRELATEDTODESCRIPTION;
#endif
#if INCLUDE_PROPERTY_ISCONSTRAINTFOR
extern property_t *PROPERTY_ISCONSTRAINTFOR;
#endif
#if INCLUDE_PROPERTY_HASREGION
extern property_t *PROPERTY_HASREGION;
#endif
#if INCLUDE_PROPERTY_NEARTO
extern property_t *PROPERTY_NEARTO;
#endif
#if INCLUDE_PROPERTY_HASPROPERTY
extern property_t *PROPERTY_HASPROPERTY;
#endif
#if INCLUDE_PROPERTY_FARFROM
extern property_t *PROPERTY_FARFROM;
#endif
#if INCLUDE_PROPERTY_FOLLOWS
extern property_t *PROPERTY_FOLLOWS;
#endif
#if INCLUDE_PROPERTY_ISDESCRIBEDBY
extern property_t *PROPERTY_ISDESCRIBEDBY;
#endif
#if INCLUDE_PROPERTY_ISPROXYFOR
extern property_t *PROPERTY_ISPROXYFOR;
#endif
#if INCLUDE_PROPERTY_ISTIMEINCLUDEDIN
extern property_t *PROPERTY_ISTIMEINCLUDEDIN;
#endif
#if INCLUDE_PROPERTY_SPECIALIZES
extern property_t *PROPERTY_SPECIALIZES;
#endif
#if INCLUDE_PROPERTY_ACTSTHROUGH
extern property_t *PROPERTY_ACTSTHROUGH;
#endif
#if INCLUDE_PROPERTY_INCONDITION
extern property_t *PROPERTY_INCONDITION;
#endif
#if INCLUDE_PROPERTY_HASDEPLOYMENT
extern property_t *PROPERTY_HASDEPLOYMENT;
#endif
#if INCLUDE_PROPERTY_INCLUDESACTION
extern property_t *PROPERTY_INCLUDESACTION;
#endif
#if INCLUDE_PROPERTY_FIRST
extern property_t *PROPERTY_FIRST;
#endif
#if INCLUDE_PROPERTY_HASPARAMETER
extern property_t *PROPERTY_HASPARAMETER;
#endif
#if INCLUDE_PROPERTY_HASMEMBER
extern property_t *PROPERTY_HASMEMBER;
#endif
#if INCLUDE_PROPERTY_HASCONSTITUENT
extern property_t *PROPERTY_HASCONSTITUENT;
#endif
#if INCLUDE_PROPERTY_FEATUREOFINTEREST
extern property_t *PROPERTY_FEATUREOFINTEREST;
#endif
#if INCLUDE_PROPERTY_ENDTIME
extern property_t *PROPERTY_ENDTIME;
#endif
#if INCLUDE_PROPERTY_ISAGENTINCLUDEDIN
extern property_t *PROPERTY_ISAGENTINCLUDEDIN;
#endif
#if INCLUDE_PROPERTY_OBSERVEDPROPERTY
extern property_t *PROPERTY_OBSERVEDPROPERTY;
#endif
#if INCLUDE_PROPERTY_ISCLASSIFIEDBY
extern property_t *PROPERTY_ISCLASSIFIEDBY;
#endif
#if INCLUDE_PROPERTY_COVERS
extern property_t *PROPERTY_COVERS;
#endif
#if INCLUDE_PROPERTY_ONPLATFORM
extern property_t *PROPERTY_ONPLATFORM;
#endif
#if INCLUDE_PROPERTY_HASPROXY
extern property_t *PROPERTY_HASPROXY;
#endif
#if INCLUDE_PROPERTY_HASINTERVALDATE
extern property_t *PROPERTY_HASINTERVALDATE;
#endif
#if INCLUDE_PROPERTY_SENSINGMETHODUSED
extern property_t *PROPERTY_SENSINGMETHODUSED;
#endif
#if INCLUDE_PROPERTY_HASPARTICIPANT
extern property_t *PROPERTY_HASPARTICIPANT;
#endif
#if INCLUDE_PROPERTY_ISQUALITYOF
extern property_t *PROPERTY_ISQUALITYOF;
#endif
#if INCLUDE_PROPERTY_ISABOUT
extern property_t *PROPERTY_ISABOUT;
#endif
#if INCLUDE_PROPERTY_USESCONCEPT
extern property_t *PROPERTY_USESCONCEPT;
#endif
#if INCLUDE_PROPERTY_HASOUTPUT
extern property_t *PROPERTY_HASOUTPUT;
#endif
#if INCLUDE_PROPERTY_ISSPECIALIZEDBY
extern property_t *PROPERTY_ISSPECIALIZEDBY;
#endif
#if INCLUDE_PROPERTY_DEFINES
extern property_t *PROPERTY_DEFINES;
#endif
#if INCLUDE_PROPERTY_REALIZESINFORMATIONABOUT
extern property_t *PROPERTY_REALIZESINFORMATIONABOUT;
#endif
#if INCLUDE_PROPERTY_HASVALUE
extern property_t *PROPERTY_HASVALUE;
#endif
#if INCLUDE_PROPERTY_ISUNIFIEDBY
extern property_t *PROPERTY_ISUNIFIEDBY;
#endif
#if INCLUDE_PROPERTY_CHARACTERIZES
extern property_t *PROPERTY_CHARACTERIZES;
#endif
#if INCLUDE_PROPERTY_REST
extern property_t *PROPERTY_REST;
#endif
#if INCLUDE_PROPERTY_HASCOMMONBOUNDARY
extern property_t *PROPERTY_HASCOMMONBOUNDARY;
#endif
#if INCLUDE_PROPERTY_COPARTICIPATESWITH
extern property_t *PROPERTY_COPARTICIPATESWITH;
#endif
#if INCLUDE_PROPERTY_ISDEFINEDIN
extern property_t *PROPERTY_ISDEFINEDIN;
#endif
#if INCLUDE_PROPERTY_HASCONSTRAINT
extern property_t *PROPERTY_HASCONSTRAINT;
#endif
#if INCLUDE_PROPERTY_OBSERVEDBY
extern property_t *PROPERTY_OBSERVEDBY;
#endif
#if INCLUDE_PROPERTY_ISREGIONFOR
extern property_t *PROPERTY_ISREGIONFOR;
#endif
#if INCLUDE_PROPERTY_OFFEATURE
extern property_t *PROPERTY_OFFEATURE;
#endif
#if INCLUDE_PROPERTY_ISREFERENCEOF
extern property_t *PROPERTY_ISREFERENCEOF;
#endif
#if INCLUDE_PROPERTY_ISCONSTITUENTOF
extern property_t *PROPERTY_ISCONSTITUENTOF;
#endif
#if INCLUDE_PROPERTY_ISPARAMETERFOR
extern property_t *PROPERTY_ISPARAMETERFOR;
#endif
#if INCLUDE_PROPERTY_DIRECTLYPRECEDES
extern property_t *PROPERTY_DIRECTLYPRECEDES;
#endif
#if INCLUDE_PROPERTY_DEFINESROLE
extern property_t *PROPERTY_DEFINESROLE;
#endif
#if INCLUDE_PROPERTY_CLASSIFIES
extern property_t *PROPERTY_CLASSIFIES;
#endif
#if INCLUDE_PROPERTY_DETECTS
extern property_t *PROPERTY_DETECTS;
#endif
#if INCLUDE_PROPERTY_ISCOMPONENTOF
extern property_t *PROPERTY_ISCOMPONENTOF;
#endif
#if INCLUDE_PROPERTY_ISSUBORDINATEDTO
extern property_t *PROPERTY_ISSUBORDINATEDTO;
#endif
#if INCLUDE_PROPERTY_ISEXECUTEDIN
extern property_t *PROPERTY_ISEXECUTEDIN;
#endif
#if INCLUDE_PROPERTY_ISCONCEPTEXPRESSEDBY
extern property_t *PROPERTY_ISCONCEPTEXPRESSEDBY;
#endif
#if INCLUDE_PROPERTY_HASREGIONDATAVALUE
extern property_t *PROPERTY_HASREGIONDATAVALUE;
#endif
#if INCLUDE_PROPERTY_HASSURVIVALRANGE
extern property_t *PROPERTY_HASSURVIVALRANGE;
#endif
#if INCLUDE_PROPERTY_ISTIMEOFOBSERVATIONOF
extern property_t *PROPERTY_ISTIMEOFOBSERVATIONOF;
#endif
#if INCLUDE_PROPERTY_ISPRODUCEDBY
extern property_t *PROPERTY_ISPRODUCEDBY;
#endif
#if INCLUDE_PROPERTY_ISMEMBEROF
extern property_t *PROPERTY_ISMEMBEROF;
#endif
#if INCLUDE_PROPERTY_ATTACHEDSYSTEM
extern property_t *PROPERTY_ATTACHEDSYSTEM;
#endif
#if INCLUDE_PROPERTY_ISACTIONINCLUDEDIN
extern property_t *PROPERTY_ISACTIONINCLUDEDIN;
#endif
#if INCLUDE_PROPERTY_ISAGENTINVOLVEDIN
extern property_t *PROPERTY_ISAGENTINVOLVEDIN;
#endif
#if INCLUDE_PROPERTY_QUALITYOFOBSERVATION
extern property_t *PROPERTY_QUALITYOFOBSERVATION;
#endif
#if INCLUDE_PROPERTY_EXECUTESTASK
extern property_t *PROPERTY_EXECUTESTASK;
#endif
#if INCLUDE_PROPERTY_DESCRIBES
extern property_t *PROPERTY_DESCRIBES;
#endif
#if INCLUDE_PROPERTY_PARAMETRIZES
extern property_t *PROPERTY_PARAMETRIZES;
#endif
#if INCLUDE_PROPERTY_HASQUALITY
extern property_t *PROPERTY_HASQUALITY;
#endif
#if INCLUDE_PROPERTY_HASDATAVALUE
extern property_t *PROPERTY_HASDATAVALUE;
#endif
#if INCLUDE_PROPERTY_ISTASKDEFINEDIN
extern property_t *PROPERTY_ISTASKDEFINEDIN;
#endif
#if INCLUDE_PROPERTY_INTRODUCES
extern property_t *PROPERTY_INTRODUCES;
#endif
#if INCLUDE_PROPERTY_ISROLEDEFINEDIN
extern property_t *PROPERTY_ISROLEDEFINEDIN;
#endif
#if INCLUDE_PROPERTY_ISINTRODUCEDBY
extern property_t *PROPERTY_ISINTRODUCEDBY;
#endif
#if INCLUDE_PROPERTY_ISCONCRETELYEXPRESSEDBY
extern property_t *PROPERTY_ISCONCRETELYEXPRESSEDBY;
#endif
#if INCLUDE_PROPERTY_EXPRESSESCONCEPT
extern property_t *PROPERTY_EXPRESSESCONCEPT;
#endif
#if INCLUDE_PROPERTY_ISCONCEPTUSEDIN
extern property_t *PROPERTY_ISCONCEPTUSEDIN;
#endif
#if INCLUDE_PROPERTY_ACTSFOR
extern property_t *PROPERTY_ACTSFOR;
#endif
#if INCLUDE_PROPERTY_VALUE
extern property_t *PROPERTY_VALUE;
#endif
#if INCLUDE_PROPERTY_ISEXPRESSEDBY
extern property_t *PROPERTY_ISEXPRESSEDBY;
#endif
#if INCLUDE_PROPERTY_ISPARAMETRIZEDBY
extern property_t *PROPERTY_ISPARAMETRIZEDBY;
#endif
#if INCLUDE_PROPERTY_OBSERVATIONRESULT
extern property_t *PROPERTY_OBSERVATIONRESULT;
#endif
#if INCLUDE_PROPERTY_HASROLE
extern property_t *PROPERTY_HASROLE;
#endif
#if INCLUDE_PROPERTY_HASLOCATION
extern property_t *PROPERTY_HASLOCATION;
#endif
#if INCLUDE_PROPERTY_INDEPLOYMENT
extern property_t *PROPERTY_INDEPLOYMENT;
#endif
#if INCLUDE_PROPERTY_SATISFIES
extern property_t *PROPERTY_SATISFIES;
#endif
#if INCLUDE_PROPERTY_INCLUDESOBJECT
extern property_t *PROPERTY_INCLUDESOBJECT;
#endif
#if INCLUDE_PROPERTY_OBSERVATIONRESULTTIME
extern property_t *PROPERTY_OBSERVATIONRESULTTIME;
#endif
#if INCLUDE_PROPERTY_HASEVENTDATE
extern property_t *PROPERTY_HASEVENTDATE;
#endif
#if INCLUDE_PROPERTY_ISLOCATIONOF
extern property_t *PROPERTY_ISLOCATIONOF;
#endif
#if INCLUDE_PROPERTY_HASTASK
extern property_t *PROPERTY_HASTASK;
#endif
#if INCLUDE_PROPERTY_MADEOBSERVATION
extern property_t *PROPERTY_MADEOBSERVATION;
#endif
#if INCLUDE_PROPERTY_DEPLOYEDSYSTEM
extern property_t *PROPERTY_DEPLOYEDSYSTEM;
#endif
#if INCLUDE_PROPERTY_ISOBJECTINCLUDEDIN
extern property_t *PROPERTY_ISOBJECTINCLUDEDIN;
#endif
#if INCLUDE_PROPERTY_EXPRESSES
extern property_t *PROPERTY_EXPRESSES;
#endif
#if INCLUDE_PROPERTY_DEFINESTASK
extern property_t *PROPERTY_DEFINESTASK;
#endif
#if INCLUDE_PROPERTY_ISCONCEPTUALIZEDBY
extern property_t *PROPERTY_ISCONCEPTUALIZEDBY;
#endif
#if INCLUDE_PROPERTY_HASPARAMETERDATAVALUE
extern property_t *PROPERTY_HASPARAMETERDATAVALUE;
#endif
#if INCLUDE_PROPERTY_DEPLOYEDONPLATFORM
extern property_t *PROPERTY_DEPLOYEDONPLATFORM;
#endif
#if INCLUDE_PROPERTY_ISSATISFIEDBY
extern property_t *PROPERTY_ISSATISFIEDBY;
#endif
#if INCLUDE_PROPERTY_ISPARTICIPANTIN
extern property_t *PROPERTY_ISPARTICIPANTIN;
#endif
#if INCLUDE_PROPERTY_HASPART
extern property_t *PROPERTY_HASPART;
#endif
#if INCLUDE_PROPERTY_ISPRECONDITIONOF
extern property_t *PROPERTY_ISPRECONDITIONOF;
#endif
#if INCLUDE_PROPERTY_ISSETTINGFOR
extern property_t *PROPERTY_ISSETTINGFOR;
#endif
#if INCLUDE_PROPERTY_IMPLEMENTEDBY
extern property_t *PROPERTY_IMPLEMENTEDBY;
#endif
#if INCLUDE_PROPERTY_ISRELATEDTOCONCEPT
extern property_t *PROPERTY_ISRELATEDTOCONCEPT;
#endif



void register_ontology();

	
#ifdef	__cplusplus
}
#endif

#endif /* _GENERATED_ONTOLOGY */
